PERIPHERALS = pwm pit
DRIVERS = usb_serial pacer nrf24 button panic ledtape adxl345

SRC = racer.c racer_motors.c radio_link.c racer_sleep.c \
      racer_radio_channel.c racer_low_voltage.c racer_heartbeat.c \
      racer_bumper.c racer_ledtape.c racer_power.c racer_fpv.c \
      racer_imu.c

include ../../boards/board.mk
