PERIPHERALS = pit
DRIVERS = pacer usb_serial adxl345 panic nrf24
SRC = hat_radio_pwm_test1.c hat_radio.c control_logic.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
