PERIPHERALS = pit pwm
DRIVERS = pacer usb_serial adxl345 panic nrf24
SRC = hat.c hat_radio.c control_logic.c bumper_hit.c radio_channel.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
