PERIPHERALS = pit pwm adc
DRIVERS = pacer usb_serial adxl345 panic nrf24 ledtape
SRC = hat.c hat_radio.c control_logic.c bumper_hit.c radio_channel.c low_voltage.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
